#!/bin/bash
# # Get Image URI from a json file generated by push.sh

WORKDIR=modules/ecs/scripts
IMAGE_URI=$(cat $WORKDIR/image_uri.json | jq .Image_URI | sed 's/"//g')
echo '{ "URI": "'"$IMAGE_URI"'" }'